POST https://user.imgrocket.cn/register
Content-Type: application/x-www-form-urlencoded

username=test3&password=123456

###
POST https://user.imgrocket.cn/login
Content-Type: application/x-www-form-urlencoded

account=hellow&password=123456

###
POST http://localhost/auto
Content-Type: application/x-www-form-urlencoded

uid=377495326&token=17BA8E27AB33297ACFC20ED665AC91B3

###
POST https://user.imgrocket.cn/register
Content-Type: application/x-www-form-urlencoded

username=测试&password=123456

###
POST https://user.imgrocket.cn/login
Content-Type: application/x-www-form-urlencoded

account=hhrlalala&password=19237912

###
POST https://user.imgrocket.cn/auto
Content-Type: application/x-www-form-urlencoded

uid=377495326&token=894C79FB81616476690B1561FF313F4C

###
POST https://user.imgrocket.cn/code/query
Content-Type: application/x-www-form-urlencoded

uid=1480416958&token=5EDFFE4FADB272E206FE8EA979F01348

###
POST https://user.imgrocket.cn/code/trail
Content-Type: application/x-www-form-urlencoded

uid=1480416958&token=5EDFFE4FADB272E206FE8EA979F01348

###
POST https://user.imgrocket.cn/code/use
Content-Type: application/x-www-form-urlencoded

uid=1480416958&token=5EDFFE4FADB272E206FE8EA979F01348&code=hhrnb

###
POST https://user.imgrocket.cn/code/task
Content-Type: application/x-www-form-urlencoded

uid=1480416958&token=5EDFFE4FADB272E206FE8EA979F01348

###
